### ISSUE TITLE
Request to make read-only

### ISSUE THREAD

**Issue by Skquark** [sarbagyastha/flutter_rating_bar#1]
I've switched between 4 different star ratings components in my Flutter project, and finally this one's my favorite.  The thing I'm missing is when I display the submitted ratings, I needed the stars to not be editable there.  Wondering if there was a way to disable interactions and make it readOnly.. Thanks.

**Comment by sarbagyastha** [comment]
Hey @Skquark ,  as per your request, [Version 1.1.1](https://pub.dartlang.org/packages/flutter_rating_bar#111) is added with __ignoreGestures__  property, which you can use to disable interactions. 😊

**Comment by Skquark** [comment]
Sweet, thanks.. Lookin good.  :thumbsup:
