### ISSUE TITLE
Incorrect star display for 0.5 rating in flutter_rating_bar

### ISSUE THREAD

**Issue by YuneshShrestha** [sarbagyastha/flutter_rating_bar#100]
I am facing a problem with the flutter_rating_bar package where it does not display the 0.5 stars correctly. If you are trying to select a 0.5 rating by clicking half stars, the widget will display full stars instead of the expected half star position. This behavior is inconsistent with the default functionality of the package, and affects the accuracy of the user evaluation in my application.

Please investigate and address this issue and ensure that the flutter_rating_bar package accurately displays fractional ratings such as 0.5 stars when users interact with it. Thank you for your attention to this.

**Comment by BunnyBuddy** [comment]
Is there a way to show rating like, 3.6 or 4.1 etc?

**Comment by BunnyBuddy** [comment]
https://stackoverflow.com/questions/62358532/flutter-rating-bar/77315320#77315320

Try the solution in the comment..

**Comment by YuneshShrestha** [comment]
Thanks for your solution. As I explored flutter_rating_bar there is RatingBar widget which fixed my issue.
