### ISSUE TITLE
Support for unrated colours

### ISSUE THREAD

**Issue by MsXam** [sarbagyastha/flutter_rating_bar#12]
I have recently upgraded from 1.1.1 to the latest version and notice a couple of issues :

a) Placing a RatingBar inside certain containers (i.e a Chip) prevents RatingBar gestures from firing.

b) It is not possible to have the colour WHITE as a rating  : 

![image](https://user-images.githubusercontent.com/18722796/62822059-26066880-bb76-11e9-8962-d6ad9eda9c49.png)

When there is a non rating, it is not possible to see this, regardless of the 'alpha' value that can be set.

**Comment by MsXam** [comment]
Note - worked in previous versions because you had support for both **fillColor** and **emptyColor** - now these have been removed because you implicitly set the unfilled/unrated colour to be an ALPHA value of 80 of the rated colour but this doesnt work in instances where the rating bar requires a WHITE rated colour or an unrated colour different to the rated colour's value as Alpha 80.

**Comment by sarbagyastha** [comment]
@MsXam will be updating the package tomorrow with the fix.

**Comment by sarbagyastha** [comment]
@MsXam [Version 2.0.0+1](https://pub.dev/packages/flutter_rating_bar#2001) now includes `unratedColor` property.

**Comment by sarbagyastha** [comment]
**Chip** internally composes of **InkWell** widget, which interferes with RatingBar's gesture detector. You may create your own Container/Material with borderRadius to achieve the same instead.

**Comment by MsXam** [comment]
This is perfect. Have tested 2.0.0+1 with the unratedColor property and works as intended.

Also , yes, 'Container with a Decoration' will allow similar LNF as Chip - so thats not an issue.

RatingBar is excellent now - thank you.

**Comment by sarbagyastha** [comment]
You're most welcome!
