### ISSUE TITLE
Unrated Color not working with new update

### ISSUE THREAD

**Issue by mrlucky96** [sarbagyastha/flutter_rating_bar#15]
The old versions worked fine with before the item builder. I am returning an amber star as an Icon and setting the unrated color as amber.withalpha(50) however they are still returning the same shade of amber.

RatingBar(
                initialRating: 2.75,
                itemCount: 5,
                itemSize: 12.0,
                itemBuilder: (context, _) => Icon(Icons.star, color: Colors.amber),
                onRatingUpdate: (rating) {
                  print(rating);
                },
                unratedColor: Colors.amber.withAlpha(50),
              ),

**Comment by sarbagyastha** [comment]
@mrlucky96 Sorry for late response.
Fixed in [**Version 3.0.0+1**](https://pub.dev/packages/flutter_rating_bar#3001).

**Comment by kmenager** [comment]
Hi @sarbagyastha,

I just try your latest version and I always have the same issue .
The star is still full white.
