### ISSUE TITLE
Icon Size

### ISSUE THREAD

**Issue by hbdejesus** [sarbagyastha/flutter_rating_bar#17]
Is there a way to make the ratings icon smaller or bigger?

**Comment by sarbagyastha** [comment]
@hbdejesus You can assign icon's size in `itemBuilder`.

```dart
RatingBar(
   initialRating: 3,
   itemBuilder: (context, _) => Icon(
     Icons.star,
     color: Colors.amber,
     size: 50,
   ),
   onRatingUpdate: (rating) {
     print(rating);
   },
);
```

**Comment by hbdejesus** [comment]
Changing the size of the icon doesn't seem to do anything in my end. 

`RatingBar(
                            initialRating: 3,
                            onRatingUpdate: (double value) {},
                            itemBuilder: (context, _) {
                              return Icon(
                                Icons.star,
                                color: Colors.amber,
                                size: 20,
                              );
                            },
                          );`

**Comment by allenind** [comment]
Up to this issue, the icon size cannot be changed! Also I would love to have this star rating to not require onRating changed, instead we can input an initial value that cannot be changed for UI purposes only!

**Comment by azamcsc** [comment]
use   itemSize: 15,
RatingBar(
                            initialRating: double.parse(tutor_rating),
                            direction: Axis.horizontal,
                            allowHalfRating: true,
                            itemCount: 5,
                            itemSize: 15,
                            itemPadding: EdgeInsets.symmetric(horizontal: 4.0),
                            itemBuilder: (context, _) => Icon(
                              Icons.star,
                              color: Colors.amber,
                            ),
                            onRatingUpdate: (rating) {
                              print(rating);
                            },
                          ),

**Comment by sarbagyastha** [comment]
@allenind , for that purpose there's **RatingBarIndicator**.

**Comment by sarbagyastha** [comment]
As @azamcsc noted, `itemSize` property can be used to adjust the icon size.
