### ISSUE TITLE
Scroll Conflict

### ISSUE THREAD

**Issue by Nstd** [sarbagyastha/flutter_rating_bar#18]
When use horizontal RatingBar in a vertical ListView, touching the rating bar to scroll up and down,  and the ListView can't move.

**Comment by therealjohnsummer** [comment]
I also have this which is a pity as this seemed like a good plugin. It appears that the gesture is not passed onto the rating bar and is stolen via the ScrollController for the ListView/SingleChildScrollView etc

**Comment by sarbagyastha** [comment]
Fixed in [**Version 3.0.0+1**](https://pub.dev/packages/flutter_rating_bar#3001).
