### ISSUE TITLE
Half rating in initial rating adds 0.5

### ISSUE THREAD

**Issue by Shakle** [sarbagyastha/flutter_rating_bar#2]
If we set for example 2.5 in initialRating and halfRating is true, widget will be created as 3.0

Probably if we create widget with initialRating 2.5 and halfRating false, it will be created as 3.5 

Thanks.

**Comment by sarbagyastha** [comment]
Issue fixed in [**Version 1.2.0**](https://pub.dev/packages/flutter_rating_bar#120)
