### ISSUE TITLE
Not Flutter Web Compatible

### ISSUE THREAD

**Issue by WanderingFire2001** [sarbagyastha/flutter_rating_bar#21]
Pub has marked this package as Web capable, but I get an exception using it with flutter web. Everything is great on Android. But on Web, I tracked the bug to the use of ColorFiltered.

Making the following change to avoid ColorFiltered, and no other change, avoids the exception (But of course that won't look like a dragging indicator--this isn't a fix, just code to show the problem is isolated to here):
```dart
class _ColorFilter extends StatelessWidget {
  final Widget child;
  final Color color;

  _ColorFilter({
    @required this.child,
    @required this.color,
  });

  @override
  Widget build(BuildContext context) {
    // ************************************************
    //  The ColorFiltered breaks WEB BUILDS
    //  kIsWeb is a property that returns true for web builds:
    //  import 'package:flutter/foundation.dart';
    // ************************************************
    if (kIsWeb) {
      return child;         // avoid the ColorFiltered wrapper to avoid throwing
    }
    return ColorFiltered(
      colorFilter: ColorFilter.mode(
        color,
        BlendMode.srcATop,
      ),
      child: ColorFiltered(
        colorFilter: ColorFilter.mode(
          Colors.white,
          BlendMode.srcATop,
        ),
        child: child,
      ),
    );
  }
}
```
I really like your widget and was happy using it until adding Web support to my app. Please let us know if you think you can implement a similar effect in a web-safe way.

If there's a way for you to indicate on Pub that this is not web compatible, please do.

I assume pub has a script that guesses which packages are Web and it misses this ColorFiltered. I'm not sure how to report it. Do you know?

**Edit: Found the relevant dev issues on Flutter github:
https://github.com/flutter/flutter/issues/40649
https://github.com/flutter/flutter/issues/47163**

**Still looking for the proper way to report it as a pub platform category mistake**

I'm using:
  flutter_rating_bar: 3.0.0+1
  Flutter (Channel dev, v1.13.7, on Microsoft Windows [Version 6.1.7601], locale en-US)

The exception text is:
```
════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following UnimplementedError was thrown during a scheduler callback:
UnimplementedError

When the exception was thrown, this was the stack: 
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 196:49  throw_
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/scene_builder.dart 173:5           pushColorFilter
package:flutter/src/rendering/layer.dart 1536:26                                                                                                                        addToScene
package:flutter/src/rendering/layer.dart 442:5                                                                                                                          [_addToSceneWithRetainedRendering]
package:flutter/src/rendering/layer.dart 1059:14                                                                                                                        addChildrenToScene
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by sahmadreza** [comment]
Hello,

I have the same issue in flutter web.

**Comment by nyilkhan** [comment]
I am having the same issue, is there any work around or is this currently not compatible with Flutter Web?

**Comment by softmarshmallow** [comment]
@sarbagyastha please update the platform tag or update as web compatitable.

**Comment by ayushin** [comment]
Whoever needs it, a temporary workaround as suggestd by @WanderingFire2001 
 

https://github.com/sarbagyastha/flutter_rating_bar/pull/32

**Comment by dvirgiln** [comment]
Hello guys, I would need this plugin with Web support. thanks

**Comment by ayushin** [comment]
We've switched to flutter_smooth_rating for now

**Comment by sarbagyastha** [comment]
The package is compatible with web now.
