### ISSUE TITLE
No rating property in RatingBar

### ISSUE THREAD

**Issue by GursheeshSingh** [sarbagyastha/flutter_rating_bar#22]
There seems to be no rating property in RatingBar widget

I was trying to make a feature where after user changed rating, I wanted to confirm if he actually wants to change the rating or not.

In case he says NO, there is no way to change the rating of the RatingBar back to original rating.

It is available in RatingBarIndicator but it read-only.

**Comment by egulhan** [comment]
Same here. After state changed, it does not update itself with new changed value.

**Comment by sarbagyastha** [comment]
You can just reset the `initialRating` value to achieve this.
