### ISSUE TITLE
Transparant unrated color

### ISSUE THREAD

**Issue by joknjokn** [sarbagyastha/flutter_rating_bar#23]
Hi,

Our UI designer is requesting the option to make the unrated stars semi-transparent.

Specifically, for a 4/5 star rating, he wants the 4 stars to be pink (works fine) and the last star transparent white. Our rating is displayed on top of an image, so it would look better than solid white/color.

Will this be possible at some point?

Thanks for the plugin by the way.

- Jonas

**Comment by sarbagyastha** [comment]
This is possible now. Sorry for the late response. Please reopen if the issue persists.
