### ISSUE TITLE
Target of URI doesn't exist

### ISSUE THREAD

**Issue by MeriemTazen** [sarbagyastha/flutter_rating_bar#3]
Hello, when I import it in my Dart file with 
` import 'package:flutter_rating_bar/flutter_rating_bar'; `

it says : 
" Target of URI doesn't exist: 'package:flutter_rating_bar/flutter_rating_bar'.
Try creating the file referenced by the URI, or Try using a URI for a file that does exist.dart(uri_does_not_exist) "

**Comment by imran-razak** [comment]
add .dart at the end
import 'package:flutter_rating_bar/flutter_rating_bar.dart';
