### ISSUE TITLE
Better error message when itemBuilder and ratingWidget not set.

### ISSUE THREAD

**Issue by mishajw** [sarbagyastha/flutter_rating_bar#30]
If neither itemBuilder or ratingWidget are set, then we get a confusing error: 

```
itemBuilder and ratingWidget can't be initialized at the same time.Either remove ratingWidget or itembuilder.
```

It should say that one has to be set.

https://github.com/sarbagyastha/flutter_rating_bar/blob/d76a41e39d41a79bdff198133da0516c36419cee/lib/flutter_rating_bar.dart#L453

**Comment by sarbagyastha** [comment]
The new version provides **RatingBar.builder** to work with `itemBuilder`.
