### ISSUE TITLE
onRatingUpdate not working for other widgets if added inside item builder.

### ISSUE THREAD

**Issue by 47BulletProof** [sarbagyastha/flutter_rating_bar#31]
onRatingUpdate not working for other widgets if added inside item builder.

**Comment by 47BulletProof** [comment]
onRatingUpdate not working for other widgets if added inside item builder.
I have added: 
`itemBuilder: (context, _) => Column(
children: [
Icon(
     Icons.star,
     color: Colors.amber,
   ),
Text('Rate')
]
),
   onRatingUpdate: (rating) {
     print(rating);
   },`

But the event only works for icon not for the whole block.
If possible, Can you please work out on this one!
Thanks.

**Comment by vinothvino42** [comment]
Yeah, I'm also getting the issue if I added the rating bar widget inside the item builder of the listview.

```
The following assertion was thrown building:
itemBuilder and ratingWidget can't be initialized at the same time.Either remove ratingWidget or itembuilder.
'package:flutter_rating_bar/flutter_rating_bar.dart':
Failed assertion: line 453 pos 11: '(itemBuilder == null && ratingWidget != null) ||
              (itemBuilder != null && ratingWidget == null)'
```

**Comment by vinothvino42** [comment]
I fixed it by adding `itemBuilder` callback in RatingBar widget.
```
itemBuilder: (context, _) => Icon(
              Icons.star,
              color: Colors.amber,
            ),
```

**Comment by sarbagyastha** [comment]
@47BulletProof The `onRatingUpdate` seems to be working fine with the column you provided above.
