### ISSUE TITLE
Can't change the size of the icons

### ISSUE THREAD

**Issue by Melak12** [sarbagyastha/flutter_rating_bar#34]
I tried to set my own size for the icons but it is not working. here is my code: 
` RatingBar(
          initialRating: 3.5,
          minRating: 1,
          direction: Axis.horizontal,
          allowHalfRating: true,
          itemCount: 5,
          itemPadding: EdgeInsets.symmetric(horizontal: 4.0),
          itemBuilder: (context, _) => Icon(
            AppIcons.star,
            color: AppColors.primary,
            size: 15.0,
          ),
          onRatingUpdate: (rating) {
            print(rating);
          },
        ),`

**Comment by ashourms** [comment]
To fix your described issue, you need to use the provided parameter named **itemSize** instead of trying to set the icon size
