### ISSUE TITLE
Only highlight the rating selected

### ISSUE THREAD

**Issue by dasmobile** [sarbagyastha/flutter_rating_bar#36]
Is it possible to only highlight the rating that's been selected, as opposed to highlighting every rating before it as well?

**Comment by nafeal3mri** [comment]
this code worked for me
`
RatingBar.builder(
                  // initialRating: 3,
                  unratedColor: Colors.black26,
                  tapOnlyMode: true,
                  itemPadding: EdgeInsets.only(right: 7, left: 7),
                  // ignoreGestures: true,

                  itemCount: 5,
                  itemSize: 40,
                  itemBuilder: (context, index) {
                    switch (index) {
                      case 0:
                        return Icon(
                          RatingFaceFont.emo_angry,
                          color: (_selectedrating - 1) == index
                              ? Colors.red
                              : Colors.black26,
                        );
                      case 1:
                        return Icon(
                          RatingFaceFont.emo_unhappy,
                          color: (_selectedrating - 1) == index
                              ? Colors.redAccent
                              : Colors.black26,
                        );
                      case 2:
                        return Icon(
                          RatingFaceFont.emo_sleep,
                          color: (_selectedrating - 1) == index
                              ? Colors.amber
                              : Colors.black26,
                        );
                      case 3:
                        return Icon(
                          RatingFaceFont.emo_happy,
                          color: (_selectedrating - 1) == index
                              ? Colors.lightGreen
                              : Colors.black26,
                        );
                      case 4:
                        return Icon(
                          RatingFaceFont.emo_thumbsup,
                          color: (_selectedrating - 1) == index
                              ? Colors.green
                              : Colors.black26,
                        );
                    }
                  },
                  onRatingUpdate: (rating) {
                    setState(() {
                      _selectedrating = rating.round();
                    });
                    print(_selectedrating);
                  })
`

**Comment by dasmobile** [comment]
> 
> 
> this code worked for me
> 
> ```dart
> RatingBar.builder(
>                   unratedColor: Colors.black26,
>                   tapOnlyMode: true,
>                   itemPadding: EdgeInsets.only(right: 7, left: 7),
>                   itemCount: 5,
>                   itemSize: 40,
>                   itemBuilder: (context, index) {
>                     switch (index) {
>                       case 0:
>                         return Icon(
>                           RatingFaceFont.emo_angry,
>                           color: (_selectedrating - 1) == index
>                               ? Colors.red
>                               : Colors.black26,
>                         );
>                       case 1:
>                         return Icon(
>                           RatingFaceFont.emo_unhappy,
>                           color: (_selectedrating - 1) == index
>                               ? Colors.redAccent
>                               : Colors.black26,
>                         );
>                       case 2:
>                         return Icon(
>                           RatingFaceFont.emo_sleep,
>                           color: (_selectedrating - 1) == index
>                               ? Colors.amber
>                               : Colors.black26,
>                         );
>                       case 3:
>                         return Icon(
>                           RatingFaceFont.emo_happy,
>                           color: (_selectedrating - 1) == index
>                               ? Colors.lightGreen
>                               : Colors.black26,
>                         );
>                       case 4:
>                         return Icon(
>                           RatingFaceFont.emo_thumbsup,
>                           color: (_selectedrating - 1) == index
>                               ? Colors.green
>                               : Colors.black26,
>                         );
>                     }
>                   },
>                   onRatingUpdate: (rating) {
>                     setState(() {
>                       _selectedrating = rating.round();
>                     });
>                   })
> ```

Thank you!  I had created a custom solution to solve the issue, but I appreciate your answer.
