### ISSUE TITLE
Animation like_button

### ISSUE THREAD

**Issue by goops17** [sarbagyastha/flutter_rating_bar#4]
I think animated button as an optional feature would be great.
Reference: https://flutterawesome.com/a-flutter-library-that-allows-you-to-create-a-button-with-animation/

**Comment by sarbagyastha** [comment]
Sorry for late response. Will definitely look into it.

**Comment by sarbagyastha** [comment]
@goops17, Check version [v2.0.0](https://pub.dev/packages/flutter_rating_bar#200)
