### ISSUE TITLE
[V3.2.0] itembuilder error

### ISSUE THREAD

**Issue by lizbrownwood** [sarbagyastha/flutter_rating_bar#44]
As I see in 3.2.0, you removed the itembuilder and the example code on pub.dev doesn't work.

**Comment by MstrZeroOne** [comment]
I have the same problem.

**Comment by sarbagyastha** [comment]
@lizbrownwood Which example code are you referring to ?

**Comment by sarbagyastha** [comment]
Reopen if the issue still perists

**Comment by devmfouad** [comment]
same problem with me

**Comment by e200** [comment]
+1

**Comment by e200** [comment]
> same problem with me

+1

**Comment by sarbagyastha** [comment]
`itemBuilder` is only accessible through `RatingBar.builder( )`.
