### ISSUE TITLE
How can i show only rate value?

### ISSUE THREAD

**Issue by barangungor** [sarbagyastha/flutter_rating_bar#45]
I want User can't rate, user only see rate value. How can i do this?

**Comment by sarbagyastha** [comment]
You can use **RatingBarIndicator**.

**Comment by barangungor** [comment]
Thanks, i think you should explain this more clearly in the plugin's description.

**Comment by barangungor** [comment]
Thanks, i think you should explain this more clearly in the plugin's description.
