### ISSUE TITLE
The named parameter 'itemBuilder' isn't defined. ???

### ISSUE THREAD

**Issue by moezzineb** [sarbagyastha/flutter_rating_bar#49]
Always getting this error on a project without any reason for the moment could you help me on this.

Cheers

**Comment by sarbagyastha** [comment]
Use `RatingBar.builder()` instead of `RatingBar()`.

**Comment by moezzineb** [comment]
Thank you so much, work like a charm.

**Comment by rj76** [comment]
@moezzineb can you provide some code how you fixed this?

**Comment by MarceloJoia** [comment]
> Use em `RatingBar.builder()`vez de `RatingBar()`.

Fucking tip.
Thank you very much. You are the man!!!
