### ISSUE TITLE
Custom image asset for Rating Bar Indicator

### ISSUE THREAD

**Issue by OliverNarramore** [sarbagyastha/flutter_rating_bar#9]
Is it possible to have a property for the rating bar indicator to utilise custom assets as is the case in the standard flutterratingbar? i.e., fullratingwidget / halfratingwidget / noratingwidget within the indicator?

**Comment by sarbagyastha** [comment]
@OliverNarramore, it is now possible in [v2.0.0](https://pub.dev/packages/flutter_rating_bar#200)
